apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: django
  template:
    metadata:
      labels:
        component: django
    spec:
      containers:
        - name: django-container
<<<<<<< HEAD
          image: aluguercio/django-backend:1.1 # pull my image from docker hub
=======
          image: aluguercio/django-backend:1.3 # pull la imagen de mi docker hub
>>>>>>> ecda68ebe6c48f3cb742a04f92c7b8a8ab839c20
          ports:
            - containerPort: 8000
          command: ["sh", "-c"]
          args: ["gunicorn backend.wsgi:application --bind 0.0.0.0:8000"]
          env:
            - name: DJANGO_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ENV
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DEBUG
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ALLOWED_HOSTS
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_ENGINE
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_HOST 
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_PORT         
---
apiVersion: v1 # django service
kind: Service
metadata:
  name: django-service
spec:
  selector:
    component: django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
