apiVersion: networking.k8s.io/v1 # ingress para redireccionar el trafico en el puerto 80 hacia react o django respectivamente
kind: Ingress
metadata:
  name: ingress
  labels: 
    name: ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
          ################
          # URL ROUTING #
          ################
          - path: /admin
            backend:
              serviceName: django-service
              servicePort: 8000
          - path: /api
            backend:
              serviceName: django-service
              servicePort: 8000
          ##########################
          # STATIC FOLDER ROUTING #
          ##########################
           - path: /static/admin/
            backend:
              serviceName: static-assets-service
              servicePort: 8000
          - path: /static/rest_framework/
            backend:
              serviceName: static-assets-service
              servicePort: 8000
          - path: /static/
            backend:
              serviceName: react-service
              servicePort: 3000
          - path: /media/
            backend:
              serviceName: react-service
              servicePort: 3000
          ################
          # URL ROUTING #
          ################
          - path: /
            backend:
              serviceName: react-service
              servicePort: 3000