apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
data:
    POSTGRES_PASSWORD: cG9zdGdyZXMtcGFzc3dvcmQ=
    DJANGO_ADMIN_PASSWORD: YWRtaW4tcGFzc3dvcmQ=
    DB_PASSWORD: cG9zdGdyZXMtcGFzc3dvcmQ=